### ISSUE TITLE
Other sbc like CM4

### ISSUE THREAD

**Issue by ProKn1fe** [DeskPi-Team/super6c#18]
Is other RPI CM4 like boards supported? Like Radxa CM3.

**Comment by avluis** [comment]
PIN compatible boards that implement most/all features should be but as 'supported' uncertain; this board was designed with the CM4 in mind so any drop-in CM4 replacements **should** work.

**Comment by eperdeme** [comment]
Anybody confirmed any other vendors fully working? Can't get raspberry CM4's anywhere.

**Comment by mengzhuo** [comment]
I can confirm that Mars-CM works

**Comment by yoyojacky** [comment]
> Is other RPI CM4 like boards supported? Like Radxa CM3.

No, Super6c supports Raspgberry Pi CM4 module ONLY.
