### ISSUE TITLE
AliExpress Deskpi store legit?

### ISSUE THREAD

**Issue by rr4444** [DeskPi-Team/super6c#19]
Hi all,

Is the AliExpress store legit for deskpi?

How do problems get addressed from China distance e.g. a dead Super6c

Thank you

**Comment by rr4444** [comment]
Hi again, really hoping to know if it is a fake, imposter DeskPi store on AliExpress...

If so, you'll want them shutdown

@yoyojacky

**Comment by yoyojacky** [comment]
hi rr4444, 
Could you please send your question to this Email: support@deskpi.com
