### ISSUE TITLE
NVME heatsink space (in unofficial or in official case)

### ISSUE THREAD

**Issue by rr4444** [DeskPi-Team/super6c#20]
Hello,

Is there space to install heatsinks on the NVME sticks, whether in the official case or unofficial ones?

Thank you!

**Comment by rr4444** [comment]
@yoyojacky Hi there, hoping you can help

I am worrying about overheating NVMEs

**Comment by yoyojacky** [comment]
hi rr4444, 
It seems have no enough space for heatsinks on back of NVMEs , our official case can provide good heat dissipation. do not worry about the temperature of NVMEs.
