### ISSUE TITLE
Issue or feature hdmi wake up fans

### ISSUE THREAD

**Issue by dzaczek** [DeskPi-Team/super6c#21]
Hi i connected pikvm to super6c. and then fans  working constantly also after poweroff board  by button , and starting after plug power to board . I realized this happens when hdmi cable is connected to board .

**Comment by yoyojacky** [comment]
> Hi i connected pikvm to super6c. and then fans working constantly also after poweroff board by button , and starting after plug power to board . I realized this happens when hdmi cable is connected to board .

You mean if the HDMI cable does not disconnect, the fan will restart to spin after power off the CM4 module ?
