### ISSUE TITLE
How to power cycle individual CM4?

### ISSUE THREAD

**Issue by Gooseman42** [DeskPi-Team/super6c#23]
I would assume that there is some way to access the power management IC STC15W408AS via I2C from any CM4 slot (similar to the Turing Pi) to power cycle any individual module?

**Comment by bigfish24** [comment]
Also interested in this for a chaos testing setup.

**Comment by derzahla** [comment]
Came here for an answer to this question. Feel unsatisfied.

**Comment by diyoyo** [comment]
I would like to learn more about this too.

**Comment by boldandbusted** [comment]
Maybe opening up the GitHub Discussions would benefit the project? :)

**Comment by tltangliang** [comment]
I'd suggest they go with the rp2040 as the power controller for the next generation, so there's enough playability.

**Comment by yoyojacky** [comment]
As I know, i do power cycle individual CM4 by using Ansible script on software, it can not do power cycle in hardware way, because all of the Raspberry Pi CM4 are connect to power core at the same time.

**Comment by yoyojacky** [comment]
> I'd suggest they go with the rp2040 as the power controller for the next generation, so there's enough playability.

Good Idea, you mean using a Raspberry Pi PICO as power controller ? it sounds interesting... LoL,
