### ISSUE TITLE
Compatiple with Orange Pi CM4

### ISSUE THREAD

**Issue by xuedi** [DeskPi-Team/super6c#26]
Is the board compatible with the Orange Pi
Compute Module 4? It seems impossible to get Raspberry Pi CM4's these days, but lots of Orange Pi's

**Comment by fiala-sns** [comment]
I am also interested in this.

**Comment by swheettaos** [comment]
bump .. the same .. it looks like it would work .. I'm more curious about the nvme .. I'm pretty sure it would work with emmc.

**Comment by yoyojacky** [comment]
/----- 
BPi CM4  has been test by this man: https://www.youtube.com/watch?v=-xSTThgtFhY
