### ISSUE TITLE
Auto-Power-On after Power Loss

### ISSUE THREAD

**Issue by SketchCND** [DeskPi-Team/super6c#5]
As this board will most likely be utilised as a server-type device and be mounted in a rack in some dark corner, is here a way to get the board to Auto-Power-On after power loss? It may not be convenient to have to physically press a button to get the board powered on if not easily accessible.

**Comment by aderesh** [comment]
The board has a switch "Always On". I haven't tested it but I assume that's what you describe. I'll try to test if I don't forget :D 
![image](https://user-images.githubusercontent.com/2285614/198928313-a67dff57-dec7-4dd6-8a9d-eccfdcc0d00b.png)
